name: Minimal tests

on: [push, pull_request]

jobs:
  stylecheck:
    name: Minimal test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Failure
        run: ./failure.sh
