name: GitHub actions

on:
  repository_dispatch: # to be triggered by upstream repo
    types: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print tag
        run: |
          echo ${{ github.event.client_payload.tag }}
