name: GitHub actions

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  repository_dispatch: # to be triggered by upstream repo
    types: [ "**" ]

permissions:
  contents: read

env:
  TEST_VAR: Spencer

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nose2

      - name: Say hello
        run: |
          echo "Hello"
          echo ${{env.TEST_VAR}}
