name: GitHub actions

on:
  repository_dispatch: # to be triggered by upstream repo
    types: [ "liboqs-release" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if tracker branch exists
        env:
          tracker_branch: ${{ github.event.client_payload.tag }}-tracker
        run: |
          curl --silent \
               --output /dev/null \
               --write-out "\n%{response_code}\n" \
               --request GET \
               --header "Accept: application/vnd.github+json" \
               --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               --header "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/swilson4/cicd-playground-downstream/branches/$tracker_branch | tee curl_out \
            && grep -q "200" curl_out \
            && echo "target_branch=$tracker_branch" >> "$GITHUB_ENV" \
            || echo "target_branch=main" >> "$GITHUB_ENV"
      - name: Checkout tracker branch if it exists, otherwise fall back to main
        uses: actions/checkout@v4
        with:
          ref: ${{ env.target_branch }}
      - name: Run tests
        run: ./release-test.sh
