name: GitHub actions

on:
  repository_dispatch: # to be triggered by upstream repo
    types: [ "liboqs-release" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if tracker branch exists
        run:
          curl --silent \
               --write-out "\n%{response_code}\n" \
               --request POST \
               --header "Accept: application/vnd.github+json" \
               --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               --header "X-GitHub-Api-Version: 2022-11-28" \
               --data '{ "event_type": "liboqs-release", "client_payload": { "tag": "${{ github.event.release.tag_name }}" } }' \
               https://api.github.com/repos/swilson4/cicd-playground-downstream/${{ github.event.client_payload.tag }}-tracker | tee curl_out \
            && grep -q "200" curl_out
      - name: Checkout tracker branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.tag }}-tracker
      - name: Run tests
        run: ./release-test.sh
