name: Release tests

on:
  repository_dispatch:
    types: [ "cicd-playground-upstream-release" ]

# To trigger this job, generate a GitHub personal access token and run the following command:
#
# curl --request POST \
#      --header "Accept: application/vnd.github+json" \
#      --header "Authorization: Bearer YOUR_TOKEN_HERE" \
#      --header "X-GitHub-Api-Version: 2022-11-28" \
#      --data '{
#                "event_type": "cicd-playground-upstream-release",
#                "client_payload": {
#                                    "provider_ref": "PROVIDER_BRANCH_OR_TAG_HERE",
#                                    "cicd-playground-upstream_ref": "LIBOQS_BRANCH_OR_TAG_HERE"
#                                  }
#              }' \
#      https://api.github.com/repos/swilson4/cicd-playground-downstream/dispatches

jobs:
  release-test:
    runs-on: ubuntu-latest
    container:
      image: openquantumsafe/ci-ubuntu-jammy:latest

    steps:
      - name: Check if requested ref exists
        env:
          provider_ref: ${{ github.event.client_payload.provider_ref }}
        run: |
          # try both branch and tag
          wget --quiet \
               --header "Accept: application/vnd.github+json" \
               --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               --header "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/swilson4/cicd-playground-downstream/branches/$provider_ref || \
          wget --quiet \
               --header "Accept: application/vnd.github+json" \
               --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               --header "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/swilson4/cicd-playground-downstream/git/ref/tags/$provider_ref \
            && echo "provider_ref=$provider_ref" >> "$GITHUB_ENV" \
            || echo "provider_ref=main" >> "$GITHUB_ENV"
      - name: Checkout cicd-playground-downstream on requested ref if it exists; otherwise, fall back to main
        uses: actions/checkout@v4
        with:
          ref: ${{ env.provider_ref }}
      # This is designed to be triggered automatically from cicd-playground-upstream CI, so don't bother validating the cicd-playground-upstream ref.
      - name: Checkout cicd-playground-upstream at requested ref
        uses: actions/checkout@v4
        with:
          repository: swilson4/cicd-playground-upstream
          path: cicd-playground-upstream
          ref: ${{ github.event.client_payload.cicd-playground-upstream_ref }}
      - name: Run release tests
        run: OPENSSL_BRANCH=master ./scripts/release-test-ci.sh
